os: osx
osx_image: xcode10
before_install:
  - brew update
  - brew upgrade node
  - brew install npm
  - brew install ios-deploy
  - xcode-select --install
  - npm install -g appium
#language: python
#python:
#  - "3.6"
# command to install dependencies
#install:
#  - pip install -r requirements.txt
# command to run tests
script:
  - echo "hello world"
  - appium
  - python3 simulatorTest.py
